### ISSUE TITLE
How to realize simulation

### ISSUE THREAD

**Issue by yinflight** [TorBorve/mpc_local_planner#1]
Demo of MPC using gazebo simulator and audibot car

**Comment by TorBorve** [comment]
This is on my todo list. This repository is a mirror of a gitlab repository for the student organization [DNV Fuel Fighter](https://www.fuelfighter.no/). The simulator is another repo on gitlab. However this is currently a bit of a mess. I'm working towards cleaning this up and making a github repo for it. 

In the meantime I can describe how to do it yourself. The simulator used is Gazebo and the [audibot repo](https://github.com/robustify/audibot/tree/noetic-devel) is used to simulate the car. The modifications done are as follows:

- Publishes current steering angle. You could also skip this and just publish "0.0" on the desired topic. However, this will effect performance.
- control system for audibot. I have implemented at control system for the car that takes in a cmd_vel message and figures out what the steering angle and throttle should be. I made this using a PID controller and the bicycle model. It is also possible to publish the steering angle directly from the mpc and publish a constant value for throttle for example.

The goal is that the mpc should work for several simulators and most importantly in the real world.

**Comment by TorBorve** [comment]
Hi again @yinflight!
I have now merged the necessary chages of audibot into the [orginal repo](https://github.com/robustify/audibot). So that is compatible with what data the MPC requires. 

Follow these steps if you want to test the mpc.
**1. Clone audibot**
```terminal
git clone https://github.com/robustify/audibot.git
```

**2. Install mpc**
Install the mpc as described in the readme.

**3. Changed params**
change `actual_steering_topic` to "/steering_state" and `map_frame` to "world" in *params/mpc.yaml*

**4. Run**
First run audibot using
```terminal
roslaunch audibot_gazebo single_vehicle_example.launch
```
In another terminal you can run the mpc
```terminal
roslaunch mpc_local_planner mpc.launch
```

Doing this the car should drive autonomously in a loop. Let me know if you have any issues.
