### ISSUE TITLE
How to Stop Planning in path_tracking_mode

### ISSUE THREAD

**Issue by chan-yuu** [TorBorve/mpc_local_planner#15]
I hope it doesn't plan at the finish point:
![2024-09-29 18-59-19 的屏幕截图](https://github.com/user-attachments/assets/a142d6fa-332e-410a-a37a-525546709b67)
(in path_tracking mode)
The car will continue to move forward:
![2024-09-29 19-02-01 的屏幕截图](https://github.com/user-attachments/assets/af819a19-efe8-4d9e-aa56-9a7bd006ff86)
How should I modify it?Please give me some advice.

**Comment by TorBorve** [comment]
In path tracking mode the mpc will continue to plan. It does not take into account that the path might stop. However, there is also a point stabilization mode. In this mode the car will drive to a specific point and have a specific orientation. This is found in `ParkingSys.h/.cpp`. Also look at `ControlSys.h/.cpp`. This class manages which mode is used.

I'm not sure what the easiest way is to implement this. 
- Suggestion 1: if you look at how the parkingSys is implemented you can see that when the vehicle is far away from the goal(parking location) then it creates a path to the goals using a bezier curve. Instead of using this you can change it to the path that you have.
- Suggestion 2: In ControlSys you can check how close you are to the end of the path. Once you are close enough you can change to parking mode. Then you need to set the goal to the last point in the path.

Hope this helps!

**Comment by chan-yuu** [comment]
Thank you for your suggestion. I will try the second option.
