### ISSUE TITLE
[ WARN] [1639745281.600672777]: Waiting for twist message. Should be published at the topic: twi st

### ISSUE THREAD

**Issue by yinflight** [TorBorve/mpc_local_planner#2]
![2021-12-17 20-49-14 的屏幕截图](https://user-images.githubusercontent.com/45703043/146547089-964f89bb-3b43-4bcb-b6ec-9d5800403913.png)

**Comment by TorBorve** [comment]
This warning is caused because that the MPC does not receive a twist message on the topic named */twist*. The twist message contains information about the velocity of the car. To manually check you can run:

``````terminal
rostopic echo /twist
``````

If no messages appear then there is a problem with the simulator/car and not the MPC. If there are messages published there could be something wrong with the MPC. I would assume that this I related to the setup of the simulator #1 .

**Comment by yinflight** [comment]
Many thanks for your kind and warm help。

**Comment by TorBorve** [comment]
You're welcome. Please let me know if let me know if you received messages when running.

```terminal
rostopic echo /twist
```

If you did not, then I will close this issue and I will refer you to issue #3 and/or #1.
